// <auto-generated />
namespace SmartRMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RestaurantAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestaurantAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202411031350545_RestaurantAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
