// <auto-generated />
namespace SmartRMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRejectionReasonToRestaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRejectionReasonToRestaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "202505041949285_AddRejectionReasonToRestaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
